import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";
import AosProvider from "@/Provider/AosProvider/AosProvider";
import Navbar from "@/Shared/Navbar";
import Footer from "@/Shared/Footer";

// Fonts
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

// Metadata
export const metadata: Metadata = {
  title: "Next Starter Template",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let faviconUrl = "/favicon.svg";

  return (
    <html lang="en">
      <head>
        <link rel="icon" href={faviconUrl} />
      </head>
      <body className={`${poppins.variable} antialiased`}>
        <AosProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
          <Toaster />
        </AosProvider>
        <Toaster />
      </body>
    </html>
  );
}
